version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:5000

  master:
    build:
      context: ./master
      dockerfile: Dockerfile
    ports:
      - 8082:5000

  chunkserver:
    build:
      context: ./chunkserver
      dockerfile: Dockerfile
    ports:
      - 8083:5000
