version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8080:5000
    environment:
      MASTER_URL: http://master:5000
      CHUNK_SIZE: 5


  master:
    build:
      context: ./master
      dockerfile: Dockerfile
    ports:
      - 8082:5000
    environment:
      CHUNKSERVERS: "http://chunkserver-1:5000,http://chunkserver-2:5000"
  
  chunkserver-1:
    image: chunkserver
    build:
      context: ./chunkserver
      dockerfile: Dockerfile
    ports:
      - 8083:5000

  chunkserver-2:
    image: chunkserver
    ports:
      - 8084:5000
